### PR TITLE
prep-html-skeleton - Henry Pham

### PR DESCRIPTION
**Pull request by hqpham98**
Screenshot 2023-09-30 at 12 51 22 PM

### CODE REVIEW

**Review by BrettAlbright — CHANGES_REQUESTED** [review]
Hey Henry, the files from the exercise are not included in the pull request. Make sure to check out the submission guide video for the git actions. one of the steps must have been missed!

**Comment by hqpham98** [comment]
Hello I made another commit with the correct files

**Review by BrettAlbright — CHANGES_REQUESTED** [review]
Nice work Henry! Make sure to answer the quiz questions as well.

**Review by BrettAlbright — APPROVED** [review]
👍🏼

**Pull request merged**
